### ISSUE TITLE
Function values are not calculated

### ISSUE THREAD

**Issue by frapontillo** [StephanHoyer/ng-translate#1]
Hello,
I think I also reported this issue a few months ago in Twitter, still... If I want to translate a function value AFTER the function returned it, the directive does not work, maybe because it doesn't call `$eval`. Is this doable? I have created a [fiddle](http://jsfiddle.net/frapontillo/cjesK/44/) starting from your example in the README.md.

**Comment by StephanHoyer** [comment]
This can be easily achieved by translating the function response

http://jsfiddle.net/cjesK/45/

**Comment by frapontillo** [comment]
From a design point of view, someone would probably prefer to keep all of the translation logic in one layer, don't you agree?

**Comment by StephanHoyer** [comment]
The translation should always be done at the point where the string occurs. You never know, what the function returns so you can't provide an appropriate translation.
