### ISSUE TITLE
Translating some element attributes also translate the element text

### ISSUE THREAD

**Issue by esquevin** [StephanHoyer/ng-translate#4]
I want to translate some title attributes, but this also force translate the content of the element, which is not the desired behavior in my case.

```
<a href="http://www.google.com" translate="title" title="Go search something">
    <i class="icon-search"></i>
</a>
```

In this case I'm using an icon and the icon is removed by the translate directive.  This may need to split the directive in 2, translate & translateAttrs

**Comment by StephanHoyer** [comment]
Hi

you are right

http://jsfiddle.net/cjesK/52/

I will fix this.

**Comment by StephanHoyer** [comment]
Ok, now it works.

You now have to add 'innerHTML' in the list, if you want to also translate the inner html. If you leave the translate atte blank, it always assumes you want to translate inner html.

Do you think this is a good solution? I also can do it with another directive.

**Comment by esquevin** [comment]
This works and has the great advantage of not breaking existing code, but it may be confusing for users if they have a translated tag and later on want to translate one attribute and forget to add innerHTML :/

But I think this will do. Thank you for your reactivity and this very usefull piece of code
