### ISSUE TITLE
Can't translate html content

### ISSUE THREAD

**Issue by esquevin** [StephanHoyer/ng-translate#5]
If the translation contains some html, it cannot be translated since the ng-translate lib uses `.text()` instead of `.html()`

http://jsfiddle.net/cjesK/58/

Moreover, the translate directive discard the existing html

**Comment by StephanHoyer** [comment]
Hi, thanks for pointing this out. I just fixed this.

Maybe it would be better to translate the single elements to avoid html tags in translation files.

**Comment by esquevin** [comment]
Sometimes you cannot avoid having html tags in your translations because its position would not be the same in different languages.
Anyhow thank you for your quick fix
